### ISSUE TITLE
Language specific class names on PRE tag.

### ISSUE THREAD

**Issue by gagan0723** [andrewbranch/gatsby-remark-vscode#43]
Is it possible to add class names on the `pre` tag depending on what language the code block is in.
Like add `language-jsx` class name if the language is in `jsx` for example.

```html
<pre class="dark-default-dark vscode-highlight language-jsx" data-language="jsx">
  <code class="vscode-highlight-code"></code>
</pre>
```

**Comment by gagan0723** [comment]
Oops 😬my bad, totally forgot that. In case someone else comes across this, here what I did:

```css
  pre:not([data-language=""]) {
    position: relative;
    padding-top: 30px;
  }
  pre:not([data-language=""])::before {
    border-radius: 0 0 4px 4px;
    color: #000;
    font-size: 0.75rem;
    letter-spacing: 0.075em;
    line-height: 1;
    padding: 0.25rem 0.5rem;
    position: absolute;
    left: 1.5rem;
    text-align: right;
    text-transform: uppercase;
    top: 0;
  }
  pre[data-language="jsx"]::before {
    content: "jsx";
    background: #61dafb;
  }
  pre[data-language="javascript"]::before {
    content: "js";
    background: #f7df1e;
  }
  pre[data-language="java"]::before {
    content: "java";
    background: #a9b7c6;
  }
  pre[data-language="rs"]::before {
    content: "rust";
    background: #f6ad54;
  }
```

Will close this now. Thanks 🙏.
