### ISSUE TITLE
Question: targeting inline code

### ISSUE THREAD

**Issue by Dajamante** [andrewbranch/gatsby-remark-vscode#45]
Another small issue:
I cannot target inline code (it is small and dull right now) that has only one backtick.

I tried chaining not()
```
code:not(.vscode-highlight):not(.vscode-highlight-code):not(.vscode-highlight-line) {
```
but it is still partly targetting vs-code.
Any work around?
<img width="731" alt="Screenshot 2019-09-07 at 21 41 30" src="https://user-images.githubusercontent.com/40670675/64479512-75ad7380-d1b8-11e9-850e-a64c806fd18e.png">

**Comment by gagan0723** [comment]
Directly targeting the `code` tag should work fine. This targets every `code` tag whether under `p`, `li` or `blockquote`, `pre` etc.

```css
code {
  color: some-color;
  background: some-color;
  padding: some-padding;
  border-radius: 3px;
}
```

One thing to note is that this will also affect `code` tag with `pre` as parent. For that you need to reset the styles on `code` tag with `pre` as parent. 

```css
pre code {
  color: inherit;
  ... other styles you need to reset
}
```
I am sure there's better way to do this, but for now that's how I do it on my website.
