### ISSUE TITLE
Line highlight comment directives stopped working in v2 alpha

### ISSUE THREAD

**Issue by janosh** [andrewbranch/gatsby-remark-vscode#70]
~It seems [my verdict](https://github.com/andrewbranch/gatsby-remark-vscode/issues/69#issuecomment-576046074) in #69 was a little premature. Looks like the line transformer for highlight comment directives isn't active or stopped working.~

Never mind what I wrote above. (You should never try to diagnose and fix bugs in a hurry. 😅) The line transformer isn't the problem. It's either the class name being attached to highlighted lines or the migration guide [which states](https://github.com/andrewbranch/gatsby-remark-vscode/blob/v2/MIGRATING.md#css-variables-and-class-names-have-changed)

> If you wrote custom CSS targeting any other class beginning with `.vscode-highlight`, replace the `.vscode-highlight` prefix with `.grvsc`. For example, `.vscode-highlight-line` is now `.grvsc-line`.

So I modified the CSS selector for highlighted lines from

```css
.vscode-highlight .vscode-highlight-line-highlighted {
  background: rgba(255, 255, 255, 0.15);
  box-shadow: inset 0.3em 0 0 0 ${props => props.theme.lighterBlue};
}
```

to

```css
.grvsc-container .grvsc-line-highlighted {
  background: rgba(255, 255, 255, 0.15);
  box-shadow: inset 0.3em 0 0 0 ${props => props.theme.lighterBlue};
}
```

The class name that's actually being applied is `grvsc-highlighted`though. Is this intentional? I think I prefer `grvsc-line-highlighted` here as it's more descriptive and specific. But we can also leave it at that and modify the migration guide.
