### ISSUE TITLE
Setting --grvsc-padding-h doesn’t change the padding

### ISSUE THREAD

**Issue by leafac** [andrewbranch/gatsby-remark-vscode#82]
I’m new to this whole CSS variables business so maybe I’m just misunderstanding how it’s supposed to work, but I’m following [the documentation](https://www.gatsbyjs.org/packages/gatsby-remark-vscode/?=vscoe#variables) and I thought that just setting `--grvsc-padding-h` would change the horizontal padding within the code block. It doesn’t.

[Here’s a simple project to demonstrate the issue](https://github.com/andrewbranch/gatsby-remark-vscode/files/4270955/variables.zip).

In `src/styles/global.css` I wrote:

```css
.grvsc-container {
  --grvsc-padding-h: 0.5rem; /* This doesn’t work. */
  --grvsc-border-radius: 3px; /* But this works, for example. */
}
```

Still, this is what I see in the browser:

<img width="300" alt="Screen Shot 2020-02-29 at 4 18 59 PM" src="https://user-images.githubusercontent.com/586813/75615231-3597cf80-5b0f-11ea-9655-a4463fee93fc.png">

And more importantly, the space I see is still `1.5rem`.

For now, the workaround is the following:

```css
.grvsc-container {
  --grvsc-padding-right: 0.5rem;
  --grvsc-padding-left: 0.5rem;
}
```

**Comment by andrewbranch** [comment]
Good catch, thanks @leafac! Fixed and published as v2.0.3.

**Comment by leafac** [comment]
Awesome. Thanks!

I noticed that you [removed from the documentation](https://github.com/andrewbranch/gatsby-remark-vscode/pull/83/files#diff-04c6e90faac2675aa89e2176d2eec7d8L296) the line saying that you can set the variables in selectors other than `:root`. I tested the following and it still works:

```css
pre {
  --grvsc-padding-v: 20px;
}
```

Can I keep using it, or should I change the selector from `pre` to `:root`?
