### ISSUE TITLE
Highlighted lines being rendered differently, according to the browser

### ISSUE THREAD

**Issue by vs0uz4** [andrewbranch/gatsby-remark-vscode#84]
Hey @andrewbranch 

When you order the printing of the post page that contains the line highlight, do these borders appear on each line depending on the browser used? Specifically the "Brave".

![Captura de tela de 2020-03-04 16-20-18](https://user-images.githubusercontent.com/2080547/75914875-43fa2a00-5e34-11ea-848f-54eff00d3200.png)

gatsby-config.js
```js
{
            resolve: `gatsby-remark-vscode`,
            options: {
              theme: {
                default: 'Solarized Light',
                parentSelector: {
                  'html[data-theme=light]': 'Solarized Light',
                  'html[data-theme=dark]': 'Dark (Visual Studio)',
                  'html[data-theme=hc]': 'High Contrast'
                },
                media: [
                  {
                    match: '(prefers-color-scheme: light)',
                    theme: 'Solarized Light'
                  },
                  {
                    match: '(prefers-color-scheme: dark)',
                    theme: 'Dark (Visual Studio)'
                  },
                  {
                    match: '(prefers-contrast: high)',
                    theme: 'High Contrast'
                  },
                  {
                    match: 'print',
                    theme: 'Light (Visual Studio)'
                  }
                ]
              },
              injectStyles: false,
              logLevel: 'warn'
            }
```
Even if I select any other theme when the media query is 'print', the edges of the lines always appear.

in google chrome
![Captura de tela de 2020-03-04 16-59-41](https://user-images.githubusercontent.com/2080547/75918462-86bf0080-5e3a-11ea-892e-2a2c1e3332f7.png)

in google chromium
![Captura de tela de 2020-03-04 16-58-22](https://user-images.githubusercontent.com/2080547/75918512-9fc7b180-5e3a-11ea-9b12-0383ef772ade.png)

in brave
![Captura de tela de 2020-03-04 16-56-52](https://user-images.githubusercontent.com/2080547/75918535-ace4a080-5e3a-11ea-8223-fe2cbdec5fee.png)

in mozilla firefox
![Captura de tela de 2020-03-04 16-55-32](https://user-images.githubusercontent.com/2080547/75918553-b7069f00-5e3a-11ea-8863-82900422d9d0.png)

in these examples above, I modified the CSS just to modify the highlighted border, placing it on both the left and right of the line. But if I leave the pattern, only on the left side the result is the same as the edges

Have you ever seen this happen? Find out by chance, as I was testing the page view in various browsers, to see if the dark and light modes were working.

**Comment by andrewbranch** [comment]
I’m not sure what’s happening here, but let’s narrow it down by starting with these three things:

- > in these examples above, I modified the CSS
  
  Does it happen when you _don’t_ modify the CSS?

- You have `injectStyles: false`. Does it happen when you delete that option?

- It looks like you copied and pasted my theme config from an issue where I was describing wild examples of what the API _could_ be used for in the future. There is no such theme called “High Contrast”; it was just an example. This makes me suspect that you might not be using the parent selector functionality at all. `(prefers-contrast: high)` is in a future draft of the CSS spec and I don’t think it’s supported by any browser right now. I would also recommend against setting a theme for `print`, too—again, it was just an example. If you just want light and dark to work, just use `theme: { default: /* pick a light theme */, dark: /* pick a dark theme */ }`.

If you do all that and can still reproduce the issue, then we’ll have a reasonable starting point to figure out what the problem is.

**Comment by vs0uz4** [comment]
- > Does it happen when you don’t modify the CSS?

sorry, I was wrong in the description. In reality, I only made the changes indicated in the documentation, to define colors for the highlighted line and the background, in addition to the thickness of the border.

excerpt indicated by the documentation
```css
:root {
  --grvsc-line-highlighted-background-color: rgba(0, 0, 0, 0.125);  /* default: transparent */
  --grvsc-line-highlighted-border-color: rgba(0, 0, 0, 0.5); /* default: transparent */
  --grvsc-line-highlighted-border-width: 4px; /* default: 4px */
}
```
And in the case of printing, I made a simple change in the question of borders, where I add a border on the right side as well.

small change to add right border
```css
/* Print mode */
@media print {
  :root {
    --grvsc-line-highlighted-background-color: rgba(0, 0, 0, 0.125); /* default: transparent */
    --grvsc-line-highlighted-border-color: rgba(0, 0, 0, 0.5); /* default: transparent */
    --grvsc-line-highlighted-border-width: 4px; /* default: 4px */
  }

  .grvsc-line-highlighted {
    background-color: var(--grvsc-line-highlighted-background-color, transparent) !important;
    box-shadow: inset var(--grvsc-line-highlighted-border-width, 4px) 0 0 0 var(--grvsc-line-highlighted-border-color, transparent), inset calc(var(--grvsc-line-highlighted-border-width, 4px) * -1) 0 0 0 var(--grvsc-line-highlighted-border-color, transparent) !important;
  }
}
```
But, even removing these changes from the borders and leaving the pattern indicated in the documentation, the problem persists, I will make the changes you suggest and perform a new test.
